version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - postgres
    environment:
      WAIT_HOSTS: postgres:5432

  #Nginx Service
  nginx:
      build:
        context:  .
        dockerfile: docker/nginx/Dockerfile
      container_name: nginx
      ports:
        - "8080:80"
      volumes:
        - ./:/var/www
      depends_on:
        - app

  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    environment:
      - "POSTGRES_DB=blinkout_db"
      - "POSTGRES_PASSWORD=root"
      - "POSTGRES_USER=root"
    ports:
      - "54325:5432"
